### ISSUE TITLE
Missing : end of the line

### ISSUE THREAD

**Issue by programmin1** [roguerb/pull-request-workshop#4]
def is missing : at end of the line. 

Funny, it kept giving me syntax errors, but I got this to work:

```
  def self.add(a, b)#:
    a + a
  end

  def self.subtract(a, b)#:
    b - a
  end
```

**Comment by seanculver** [comment]
Can you submit a PR for these changes. Thanks!

**Comment by conroywhitney** [comment]
Hey @programmin1. Thanks for looking into making this project better!

Actually, the `:`s would be for python. In ruby we don't need anything at the end of the method definition.

Most likely, the reason that it worked with the `#` is because that's the ruby version of a comment -- so it would have ignored the `:` afterwards.

Let us know if you find anything else we need to address.
